//
//  Global.h
//  Ganaz
//
//  Created by Piric Djordje on 2/18/17.
//  Copyright © 2017 Ganaz. All rights reserved.
//

#ifndef Global_h
#define Global_h
 
#import <Crashlytics/Crashlytics.h>

//#warning This should be removed before submission!
//#define GANENVIRONMENT_STAGING

// BASE URL                                                                                                                                                                                                                                                   

#define GANURL_GATEWAY                              @"http://34.210.176.28"

#if     defined(GANENVIRONMENT_STAGING)

#define ONESIGNAL_APPID                             @"ade7e4b5-b439-4d82-9bb2-c040372c1f14"
#define GANURL_BASEURL                              @"http://34.209.77.248:8000/api/v1"
#define MIXPANEL_PROJECTTOKEN                       @"d1bee23a670fbbe63a19373daba332b0"

#define GANLOG( s, ... ) NSLog( @"%s: %@ l=>%d", __FUNCTION__, [NSString stringWithFormat:(s), ##__VA_ARGS__], __LINE__ )
//#define GANLOG( s, ... ) CLS_LOG( @"%s: %@ l=>%d", __FUNCTION__, [NSString stringWithFormat:(s), ##__VA_ARGS__], __LINE__ )

#elif   defined(GANENVIRONMENT_DEMO)

#define ONESIGNAL_APPID                             @"37c1d731-1cbd-40cf-9ba3-3936174602e1"
#define GANURL_BASEURL                              @"http://34.210.63.91:8000/api/v1"
#define MIXPANEL_PROJECTTOKEN                       @"3f0f41f4cfc0c55f1762ef08f7692b86"

#define GANLOG( s, ... ) CLS_LOG( @"%s: %@ l=>%d", __FUNCTION__, [NSString stringWithFormat:(s), ##__VA_ARGS__], __LINE__ )

#else

#define ONESIGNAL_APPID                             @"160b5387-8178-46e2-b194-ad193dc5efac"
#define GANURL_BASEURL                              @"http://35.160.103.25:8000/api/v1"
#define MIXPANEL_PROJECTTOKEN                       @"50fffae37bad52c48cf0e691f36cd1a4"

#define GANLOG( s, ... ) CLS_LOG( @"%s: %@ l=>%d", __FUNCTION__, [NSString stringWithFormat:(s), ##__VA_ARGS__], __LINE__ )

#endif


#define GANACTIVITY_REPORT(s) [[GANAppManager sharedInstance] logActivity: (s) ]


#define GANURL_APPSTORE                             @"itms://itunes.apple.com/us/app/apple-store/id1230180278?mt=8"

// CONSTANTS

#define TRANSITION_FADEOUT_DURATION                         0.25f

#define GANLOCATION_DEFAULT_LATITUDE                        40.7128
#define GANLOCATION_DEFAULT_LONGITUDE                       -74.0059

#define GANNEARBY_DEFAULT_RADIUS                            50
#define GANNEARBY_MIN_WORKERS_COUNT                         20

#define GOOGLEMAPS_API_KEY                                  @"AIzaSyCrYm3QN8cfIN5rbGcFHBEGSAye8G4lUho"
#define GOOGLE_TRANSLATE_API_KEY                            @"AIzaSyCVm0nvaYBqtNOOepzALr7iCKNW1_96J6o"

// UICOLOR

#define GANUICOLOR_THEMECOLOR_MAIN                              [UIColor colorWithRed:(51 / 255.0) green:(51 / 255.0) blue:(51 / 255.0) alpha:1]
#define GANUICOLOR_THEMECOLOR_GREEN                             [UIColor colorWithRed:(100 / 255.0) green:(179 / 255.0) blue:(31 / 255.0) alpha:1]
#define GANUICOLOR_THEMECOLOR_TABBAR_SELECTED                   [UIColor colorWithRed:(67 / 255.0) green:(137 / 255.0) blue:(6 / 255.0) alpha:1]
#define GANUICOLOR_THEMECOLOR_PLACEHOLDER                       [UIColor colorWithRed:(255 / 255.0) green:(255 / 255.0) blue:(255 / 255.0) alpha:0.5]
#define GANUICOLOR_UIBUTTON_DELETE_BORDERCOLOR                  [UIColor colorWithRed:(51 / 255.0) green:(51 / 255.0) blue:(51 / 255.0) alpha:0.6]
#define GANUICOLOR_BADGE_GOLD                                   [UIColor colorWithRed:(251 / 255.0) green:(205 / 255.0) blue:(67 / 255.0) alpha:1]
#define GANUICOLOR_BADGE_SILVER                                 [UIColor colorWithRed:(209 / 255.0) green:(217 / 255.0) blue:(223 / 255.0) alpha:1]

// Error Code

#define SUCCESS_WITH_NO_ERROR                       200
#define SUCCESS_WITH_CREATE                         201

#define ERROR_BAD_REQUEST                           400
#define ERROR_UNAUTHORIZED                          401
#define ERROR_FORBIDDEN                             403
#define ERROR_NOT_FOUND                             404
#define ERROR_VERSION_EXPIRED                       412
#define ERROR_USER_NEWDEVICE                        419
#define ERROR_USER_DISABLED                         420
#define ERROR_REQUEST_FLOOD                         429
#define ERROR_USER_INVALID_PHONECARRIER             461
#define ERROR_USER_INVALID_PHONENUMBER              462
#define ERROR_CONNECTION_FAILED                     499
#define ERROR_INTERNAL_SERVER_ERROR                 500
#define ERROR_UNKNOWN                               520
#define ERROR_MAINTENANCE_MODE                      555

#define ERROR_USER_SIGNUPFAILED_USERNAMECONFLICT    1001
#define ERROR_USER_SIGNUPFAILED_EMAILCONFLICT       1002
#define ERROR_USER_SIGNUPFAILED_PHONENUMBERCONFLICT 1003
#define ERROR_USER_LOGINFAILED_USERNOTFOUND         1004
#define ERROR_USER_LOGINFAILED_PASSWORDWRONG        1005

#define GANLOCALNOTIFICATION_USER_SILENTLOGIN_SUCCEEDED                 @"GANLOCALNOTIFICATION_USER_SILENTLOGIN_SUCCEEDED"
#define GANLOCALNOTIFICATION_USER_SILENTLOGIN_FAILED                    @"GANLOCALNOTIFICATION_USER_SILENTLOGIN_FAILED"
#define GANLOCALNOTIFICATION_COMPANY_JOBLIST_UPDATED                    @"GANLOCALNOTIFICATION_COMPANY_JOBLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_JOBLIST_UPDATEFAILED               @"GANLOCALNOTIFICATION_COMPANY_JOBLIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_COMPANY_COMPANYUSERSLIST_UPDATED           @"GANLOCALNOTIFICATION_COMPANY_COMPANYUSERSLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_COMPANYUSERSLIST_UPDATEFAILED      @"GANLOCALNOTIFICATION_COMPANY_COMPANYUSERSLIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_COMPANY_CREWSLIST_UPDATED                  @"GANLOCALNOTIFICATION_COMPANY_CREWSLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_CREWSLIST_UPDATEFAILED             @"GANLOCALNOTIFICATION_COMPANY_CREWSLIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_COMPANY_MYWORKERSLIST_UPDATED              @"GANLOCALNOTIFICATION_COMPANY_MYWORKERSLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_MYWORKERSLIST_UPDATEFAILED         @"GANLOCALNOTIFICATION_COMPANY_MYWORKERSLIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_MESSAGE_LIST_UPDATED                       @"GANLOCALNOTIFICATION_MESSAGE_LIST_UPDATED"
#define GANLOCALNOTIFICATION_MESSAGE_LIST_UPDATEFAILED                  @"GANLOCALNOTIFICATION_MESSAGE_LIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_WORKER_JOBSEARCH_UPDATED                   @"GANLOCALNOTIFICATION_WORKER_JOBSEARCH_UPDATED"
#define GANLOCALNOTIFICATION_WORKER_JOBSEARCH_UPDATEFAILED              @"GANLOCALNOTIFICATION_WORKER_JOBSEARCH_UPDATEFAILED"
#define GANLOCALNOTIFICATION_WORKER_JOBSEARCH_FILTER_UPDATED            @"GANLOCALNOTIFICATION_WORKER_JOBSEARCH_FILTER_UPDATED"
#define GANLOCALNOTIFICATION_REVIEW_LIST_UPDATED                        @"GANLOCALNOTIFICATION_REVIEW_LIST_UPDATED"
#define GANLOCALNOTIFICATION_REVIEW_LIST_UPDATE_FAILED                  @"GANLOCALNOTIFICATION_REVIEW_LIST_UPDATE_FAILED"
#define GANLOCALNOTIFICATION_LOCATION_UPDATED                           @"GANLOCALNOTIFICATION_LOCATION_UPDATED"
#define GANLOCALNOTIFICATION_CONTENTS_TRANSLATED                        @"GANLOCALNOTIFICATION_CONTENTS_TRANSLATED"
#define GANLOCALNOTIFICATION_MEMBERSHIPPLAN_LIST_UPDATED                @"GANLOCALNOTIFICATION_MEMBERSHIPPLAN_LIST_UPDATED"
#define GANLOCALNOTIFICATION_MEMBERSHIPPLAN_LIST_UPDATE_FAILED          @"GANLOCALNOTIFICATION_MEMBERSHIPPLAN_LIST_UPDATE_FAILED"
#define GANLOCALNOTIFICATION_COMPANY_SURVEYLIST_UPDATED                 @"GANLOCALNOTIFICATION_COMPANY_SURVEYLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_SURVEYLIST_UPDATEFAILED            @"GANLOCALNOTIFICATION_COMPANY_SURVEYLIST_UPDATEFAILED"
#define GANLOCALNOTIFICATION_COMPANY_SURVEYANSWERLIST_UPDATED           @"GANLOCALNOTIFICATION_COMPANY_SURVEYANSWERLIST_UPDATED"
#define GANLOCALNOTIFICATION_COMPANY_SURVEYANSWERLIST_UPDATEFAILED      @"GANLOCALNOTIFICATION_COMPANY_SURVEYANSWERLIST_UPDATEFAILED"

#define GANLOCALNOTIFICATION_ONBOARDINGACTION_WORKER_JOBAPPLY           @"GANLOCALNOTIFICATION_ONBOARDINGACTION_WORKER_JOBAPPLY"
#define GANLOCALNOTIFICATION_ONBOARDINGACTION_WORKER_SUGGESTFRIEND      @"GANLOCALNOTIFICATION_ONBOARDINGACTION_WORKER_SUGGESTFRIEND"

#define GANLOCALNOTIFICATION_DEEPLINK_ANALYZECOMPLETED                  @"GANLOCALNOTIFICATION_DEEPLINK_ANALYZECOMPLETED"

#define LOCALSTORAGE_PREFIX                                             @"GANAZLOCALSTORAGE_"
#define LOCALSTORAGE_USER_LOGIN                                         @"USER_LOGIN"

#endif /* Global_h */
